dist: trusty
language: java
jdk:
  - oraclejdk8  # LTS until Mar 2022
  - oraclejdk11 # LTS until Sep 2023
  - oraclejdk15 # out of support
  - oraclejdk16 # out of support
  - oraclejdk17 # LTS until Sep 2026
jobs:
  include:
    # Extra job, testing legacy CMM option
    - jdk: oraclejdk8
      env: MAVEN_OPTS=-Dsun.java2d.cmm=sun.java2d.cmm.kcms.KcmsServiceProvider
cache:
  directories:
  - $HOME/.m2
