<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.twelvemonkeys.imageio</groupId>
        <artifactId>imageio</artifactId>
        <version>3.12.1-SNAPSHOT</version>
    </parent>
    <artifactId>imageio-heic</artifactId>
    <name>TwelveMonkeys :: ImageIO :: HEIC plugin</name>
    <description>
        ImageIO plugin for ISO/IEC 23008-12:2017 HEIF file format
    </description>

    <properties>
        <project.jpms.module.name>com.twelvemonkeys.imageio.plugins</project.jpms.module.name>
    </properties>

    <repositories>
        <repository>
            <id>aspose-maven-repository</id>
            <url>https://repository.aspose.com/repo/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>com.twelvemonkeys.imageio</groupId>
            <artifactId>imageio-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.twelvemonkeys.imageio</groupId>
            <artifactId>imageio-core</artifactId>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.twelvemonkeys.imageio</groupId>
            <artifactId>imageio-metadata</artifactId>
        </dependency>
        <dependency>
            <groupId>openize</groupId>
            <artifactId>openize-heic</artifactId>
            <version>25.6</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
                <configuration>
                    <instructions>
                        <Provide-Capability>
                            osgi.serviceloader;
                            osgi.serviceloader=javax.imageio.spi.ImageReaderSpi
                        </Provide-Capability>
                    </instructions>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
